
name: Py-Pypr CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v5
      # - name: Install project
      #   run: |
      #     uv pip install --system . 
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run tests
        run: |
          uv run pytest tests


